apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-deployment
  namespace: istio
spec:
  selector:
    matchLabels:
      app: istio
  replicas: 3
  template:
    metadata:
      labels:
        app: istio
    spec:
      containers:
      - name: istio
        image: mrcherries/dummy_exporter:v1
        ports:
        - containerPort: 8000